/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "/home/lionel/EURECOM/CODE/openair-cn.prose.clean/src/s1ap/messages/asn1/r15/s1ap-15.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D /home/lionel/EURECOM/CODE/openair-cn.prose.clean/src/s1ap/messages/asn1/r15/GENERATED_S1AP`
 */

#include "S1AP_E-RAB-IE-ContainerList.h"

int
S1AP_E_RAB_IE_ContainerList_1165P0_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P0,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P1_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P1,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P2,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P3,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P4_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P4,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P5_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P5,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P6_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P6,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P7_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P7,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P8_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P8,
 * so here we adjust the DEF accordingly.
 */
int
S1AP_E_RAB_IE_ContainerList_1165P9_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 256)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using S1AP_ProtocolIE_ContainerList_6876P9,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P1_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P2_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P3_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P4_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P5_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P6_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P7_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P8_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P9_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P0_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P0_constr_1, S1AP_E_RAB_IE_ContainerList_1165P0_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P0_1,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P1_tags_2[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P1_constr_2, S1AP_E_RAB_IE_ContainerList_1165P1_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P1_3,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P1_specs_3	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P2_tags_3[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P2_constr_3, S1AP_E_RAB_IE_ContainerList_1165P2_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P2_5,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P2_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P3_tags_4[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P3_constr_4, S1AP_E_RAB_IE_ContainerList_1165P3_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P3_7,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P3_specs_7	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P4_tags_5[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P4_constr_5, S1AP_E_RAB_IE_ContainerList_1165P4_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P4_9,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P4_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P5_tags_6[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P5_constr_6, S1AP_E_RAB_IE_ContainerList_1165P5_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P5_11,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P5_specs_11	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P6_tags_7[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P6_constr_7, S1AP_E_RAB_IE_ContainerList_1165P6_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P6_13,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P6_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P7_tags_8[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P7_constr_8, S1AP_E_RAB_IE_ContainerList_1165P7_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P7_15,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P7_specs_15	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P8_tags_9[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P8_constr_9, S1AP_E_RAB_IE_ContainerList_1165P8_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P8_17,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P8_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10,
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10[0]), /* 1 */
	asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10)
		/sizeof(asn_DEF_S1AP_E_RAB_IE_ContainerList_1165P9_tags_10[0]), /* 1 */
	{ 0, &asn_PER_type_S1AP_E_RAB_IE_ContainerList_1165P9_constr_10, S1AP_E_RAB_IE_ContainerList_1165P9_constraint },
	asn_MBR_S1AP_ProtocolIE_ContainerList_6876P9_19,
	1,	/* Single element */
	&asn_SPC_S1AP_ProtocolIE_ContainerList_6876P9_specs_19	/* Additional specs */
};

