/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "/home/lionel/EURECOM/CODE/openair-cn.prose.clean/src/s1ap/messages/asn1/r15/s1ap-15.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D /home/lionel/EURECOM/CODE/openair-cn.prose.clean/src/s1ap/messages/asn1/r15/GENERATED_S1AP`
 */

#ifndef	_S1AP_ProtocolExtensionContainer_H_
#define	_S1AP_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1AP_E_RABDataForwardingItem_ExtIEs;
struct S1AP_E_RABToBeSetupItemHOReq_ExtIEs;
struct S1AP_E_RABAdmittedItem_ExtIEs;
struct S1AP_E_RABFailedToSetupItemHOReqAckExtIEs;
struct S1AP_E_RABToBeSwitchedDLItem_ExtIEs;
struct S1AP_E_RABToBeSwitchedULItem_ExtIEs;
struct S1AP_E_RABToBeSetupItemBearerSUReqExtIEs;
struct S1AP_E_RABSetupItemBearerSUResExtIEs;
struct S1AP_E_RABToBeModifyItemBearerModReqExtIEs;
struct S1AP_E_RABModifyItemBearerModResExtIEs;
struct S1AP_E_RABReleaseItemBearerRelCompExtIEs;
struct S1AP_E_RABToBeSetupItemCtxtSUReqExtIEs;
struct S1AP_E_RABSetupItemCtxtSUResExtIEs;
struct S1AP_TAIItemExtIEs;
struct S1AP_E_RABToBeModifiedItemBearerModInd_ExtIEs;
struct S1AP_E_RABNotToBeModifiedItemBearerModInd_ExtIEs;
struct S1AP_CSGMembershipInfo_ExtIEs;
struct S1AP_E_RABModifyItemBearerModConfExtIEs;
struct S1AP_E_RABFailedToResumeItemResumeReq_ExtIEs;
struct S1AP_E_RABFailedToResumeItemResumeRes_ExtIEs;
struct S1AP_Additional_GUTI_ExtIEs;
struct S1AP_AllocationAndRetentionPriority_ExtIEs;
struct S1AP_InformationForCECapableUEs_ExtIEs;
struct S1AP_AssistanceDataForPaging_ExtIEs;
struct S1AP_AssistanceDataForRecommendedCells_ExtIEs;
struct S1AP_Bearers_SubjectToStatusTransfer_ItemExtIEs;
struct S1AP_CancelledCellinEAI_Item_ExtIEs;
struct S1AP_CancelledCellinTAI_Item_ExtIEs;
struct S1AP_CellIdentifierAndCELevelForCECapableUEs_ExtIEs;
struct S1AP_CellID_Broadcast_Item_ExtIEs;
struct S1AP_CellID_Cancelled_Item_ExtIEs;
struct S1AP_CellBasedMDT_ExtIEs;
struct S1AP_CellBasedQMC_ExtIEs;
struct S1AP_Cdma2000OneXSRVCCInfo_ExtIEs;
struct S1AP_CellType_ExtIEs;
struct S1AP_CGI_ExtIEs;
struct S1AP_CSG_IdList_Item_ExtIEs;
struct S1AP_COUNTvalue_ExtIEs;
struct S1AP_COUNTValueExtended_ExtIEs;
struct S1AP_COUNTvaluePDCP_SNlength18_ExtIEs;
struct S1AP_CriticalityDiagnostics_ExtIEs;
struct S1AP_CriticalityDiagnostics_IE_Item_ExtIEs;
struct S1AP_ServedDCNsItem_ExtIEs;
struct S1AP_DL_CP_SecurityInformation_ExtIEs;
struct S1AP_EmergencyAreaID_Broadcast_Item_ExtIEs;
struct S1AP_EmergencyAreaID_Cancelled_Item_ExtIEs;
struct S1AP_CompletedCellinEAI_Item_ExtIEs;
struct S1AP_GERAN_Cell_ID_ExtIEs;
struct S1AP_GlobalENB_ID_ExtIEs;
struct S1AP_ENB_StatusTransfer_TransparentContainer_ExtIEs;
struct S1AP_E_RABInformationListItem_ExtIEs;
struct S1AP_E_RABItem_ExtIEs;
struct S1AP_E_RABQoSParameters_ExtIEs;
struct S1AP_E_RABUsageReportItem_ExtIEs;
struct S1AP_EUTRAN_CGI_ExtIEs;
struct S1AP_ExpectedUEBehaviour_ExtIEs;
struct S1AP_ExpectedUEActivityBehaviour_ExtIEs;
struct S1AP_ForbiddenTAs_Item_ExtIEs;
struct S1AP_ForbiddenLAs_Item_ExtIEs;
struct S1AP_GBR_QosInformation_ExtIEs;
struct S1AP_GUMMEI_ExtIEs;
struct S1AP_HandoverRestrictionList_ExtIEs;
struct S1AP_ImmediateMDT_ExtIEs;
struct S1AP_InformationOnRecommendedCellsAndENBsForPaging_ExtIEs;
struct S1AP_LAI_ExtIEs;
struct S1AP_LastVisitedEUTRANCellInformation_ExtIEs;
struct S1AP_ListeningSubframePattern_ExtIEs;
struct S1AP_LoggedMDT_ExtIEs;
struct S1AP_LoggedMBSFNMDT_ExtIEs;
struct S1AP_M3Configuration_ExtIEs;
struct S1AP_M4Configuration_ExtIEs;
struct S1AP_M5Configuration_ExtIEs;
struct S1AP_M6Configuration_ExtIEs;
struct S1AP_M7Configuration_ExtIEs;
struct S1AP_MDT_Configuration_ExtIEs;
struct S1AP_MBSFN_ResultToLogInfo_ExtIEs;
struct S1AP_MutingPatternInformation_ExtIEs;
struct S1AP_NB_IoT_Paging_eDRXInformation_ExtIEs;
struct S1AP_NRUESecurityCapabilities_ExtIEs;
struct S1AP_PagingAttemptInformation_ExtIEs;
struct S1AP_Paging_eDRXInformation_ExtIEs;
struct S1AP_M1PeriodicReporting_ExtIEs;
struct S1AP_PLMNAreaBasedQMC_ExtIEs;
struct S1AP_ProSeAuthorized_ExtIEs;
struct S1AP_RecommendedCellsForPaging_ExtIEs;
struct S1AP_RecommendedCellsForPagingItem_ExtIEs;
struct S1AP_RecommendedENBsForPaging_ExtIEs;
struct S1AP_RecommendedENBItem_ExtIEs;
struct S1AP_RequestType_ExtIEs;
struct S1AP_RIMTransfer_ExtIEs;
struct S1AP_RLFReportInformation_ExtIEs;
struct S1AP_SecurityContext_ExtIEs;
struct S1AP_SecondaryRATDataUsageReportItem_ExtIEs;
struct S1AP_SONInformationReply_ExtIEs;
struct S1AP_SONConfigurationTransfer_ExtIEs;
struct S1AP_SynchronisationInformation_ExtIEs;
struct S1AP_SourceeNB_ID_ExtIEs;
struct S1AP_SourceeNB_ToTargeteNB_TransparentContainer_ExtIEs;
struct S1AP_ServedGUMMEIsItem_ExtIEs;
struct S1AP_SupportedTAs_Item_ExtIEs;
struct S1AP_TimeSynchronisationInfo_ExtIEs;
struct S1AP_S_TMSI_ExtIEs;
struct S1AP_TAIBasedMDT_ExtIEs;
struct S1AP_TAI_ExtIEs;
struct S1AP_TAI_Broadcast_Item_ExtIEs;
struct S1AP_TAI_Cancelled_Item_ExtIEs;
struct S1AP_TABasedMDT_ExtIEs;
struct S1AP_TABasedQMC_ExtIEs;
struct S1AP_TAIBasedQMC_ExtIEs;
struct S1AP_CompletedCellinTAI_Item_ExtIEs;
struct S1AP_TargeteNB_ID_ExtIEs;
struct S1AP_TargetRNC_ID_ExtIEs;
struct S1AP_TargeteNB_ToSourceeNB_TransparentContainer_ExtIEs;
struct S1AP_M1ThresholdEventA2_ExtIEs;
struct S1AP_TraceActivation_ExtIEs;
struct S1AP_Tunnel_Information_ExtIEs;
struct S1AP_UEAggregate_MaximumBitrates_ExtIEs;
struct S1AP_UEAppLayerMeasConfig_ExtIEs;
struct S1AP_UE_S1AP_ID_pair_ExtIEs;
struct S1AP_UE_associatedLogicalS1_ConnectionItemExtIEs;
struct S1AP_UESecurityCapabilities_ExtIEs;
struct S1AP_UE_Sidelink_Aggregate_MaximumBitrates_ExtIEs;
struct S1AP_UL_CP_SecurityInformation_ExtIEs;
struct S1AP_UserLocationInformation_ExtIEs;
struct S1AP_V2XServicesAuthorized_ExtIEs;
struct S1AP_X2TNLConfigurationInfo_ExtIEs;
struct S1AP_ENBX2ExtTLA_ExtIEs;

/* S1AP_ProtocolExtensionContainer */
typedef struct S1AP_ProtocolExtensionContainer_6890P0 {
	A_SEQUENCE_OF(struct S1AP_E_RABDataForwardingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P0_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P1 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeSetupItemHOReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P1_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P2 {
	A_SEQUENCE_OF(struct S1AP_E_RABAdmittedItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P2_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P3 {
	A_SEQUENCE_OF(struct S1AP_E_RABFailedToSetupItemHOReqAckExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P3_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P4 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeSwitchedDLItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P4_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P5 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeSwitchedULItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P5_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P6 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeSetupItemBearerSUReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P6_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P7 {
	A_SEQUENCE_OF(struct S1AP_E_RABSetupItemBearerSUResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P7_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P8 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeModifyItemBearerModReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P8_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P9 {
	A_SEQUENCE_OF(struct S1AP_E_RABModifyItemBearerModResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P9_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P10 {
	A_SEQUENCE_OF(struct S1AP_E_RABReleaseItemBearerRelCompExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P10_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P11 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeSetupItemCtxtSUReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P11_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P12 {
	A_SEQUENCE_OF(struct S1AP_E_RABSetupItemCtxtSUResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P12_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P13 {
	A_SEQUENCE_OF(struct S1AP_TAIItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P13_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P14 {
	A_SEQUENCE_OF(struct S1AP_E_RABToBeModifiedItemBearerModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P14_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P15 {
	A_SEQUENCE_OF(struct S1AP_E_RABNotToBeModifiedItemBearerModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P15_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P16 {
	A_SEQUENCE_OF(struct S1AP_CSGMembershipInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P16_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P17 {
	A_SEQUENCE_OF(struct S1AP_E_RABModifyItemBearerModConfExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P17_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P18 {
	A_SEQUENCE_OF(struct S1AP_E_RABFailedToResumeItemResumeReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P18_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P19 {
	A_SEQUENCE_OF(struct S1AP_E_RABFailedToResumeItemResumeRes_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P19_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P20 {
	A_SEQUENCE_OF(struct S1AP_Additional_GUTI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P20_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P21 {
	A_SEQUENCE_OF(struct S1AP_AllocationAndRetentionPriority_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P21_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P22 {
	A_SEQUENCE_OF(struct S1AP_InformationForCECapableUEs_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P22_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P23 {
	A_SEQUENCE_OF(struct S1AP_AssistanceDataForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P23_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P24 {
	A_SEQUENCE_OF(struct S1AP_AssistanceDataForRecommendedCells_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P24_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P25 {
	A_SEQUENCE_OF(struct S1AP_Bearers_SubjectToStatusTransfer_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P25_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P26 {
	A_SEQUENCE_OF(struct S1AP_CancelledCellinEAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P26_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P27 {
	A_SEQUENCE_OF(struct S1AP_CancelledCellinTAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P27_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P28 {
	A_SEQUENCE_OF(struct S1AP_CellIdentifierAndCELevelForCECapableUEs_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P28_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P29 {
	A_SEQUENCE_OF(struct S1AP_CellID_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P29_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P30 {
	A_SEQUENCE_OF(struct S1AP_CellID_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P30_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P31 {
	A_SEQUENCE_OF(struct S1AP_CellBasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P31_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P32 {
	A_SEQUENCE_OF(struct S1AP_CellBasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P32_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P33 {
	A_SEQUENCE_OF(struct S1AP_Cdma2000OneXSRVCCInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P33_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P34 {
	A_SEQUENCE_OF(struct S1AP_CellType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P34_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P35 {
	A_SEQUENCE_OF(struct S1AP_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P35_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P36 {
	A_SEQUENCE_OF(struct S1AP_CSG_IdList_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P36_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P37 {
	A_SEQUENCE_OF(struct S1AP_COUNTvalue_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P37_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P38 {
	A_SEQUENCE_OF(struct S1AP_COUNTValueExtended_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P38_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P39 {
	A_SEQUENCE_OF(struct S1AP_COUNTvaluePDCP_SNlength18_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P39_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P40 {
	A_SEQUENCE_OF(struct S1AP_CriticalityDiagnostics_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P40_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P41 {
	A_SEQUENCE_OF(struct S1AP_CriticalityDiagnostics_IE_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P41_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P42 {
	A_SEQUENCE_OF(struct S1AP_ServedDCNsItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P42_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P43 {
	A_SEQUENCE_OF(struct S1AP_DL_CP_SecurityInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P43_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P44 {
	A_SEQUENCE_OF(struct S1AP_EmergencyAreaID_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P44_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P45 {
	A_SEQUENCE_OF(struct S1AP_EmergencyAreaID_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P45_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P46 {
	A_SEQUENCE_OF(struct S1AP_CompletedCellinEAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P46_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P47 {
	A_SEQUENCE_OF(struct S1AP_GERAN_Cell_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P47_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P48 {
	A_SEQUENCE_OF(struct S1AP_GlobalENB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P48_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P49 {
	A_SEQUENCE_OF(struct S1AP_ENB_StatusTransfer_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P49_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P50 {
	A_SEQUENCE_OF(struct S1AP_E_RABInformationListItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P50_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P51 {
	A_SEQUENCE_OF(struct S1AP_E_RABItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P51_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P52 {
	A_SEQUENCE_OF(struct S1AP_E_RABQoSParameters_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P52_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P53 {
	A_SEQUENCE_OF(struct S1AP_E_RABUsageReportItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P53_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P54 {
	A_SEQUENCE_OF(struct S1AP_EUTRAN_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P54_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P55 {
	A_SEQUENCE_OF(struct S1AP_ExpectedUEBehaviour_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P55_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P56 {
	A_SEQUENCE_OF(struct S1AP_ExpectedUEActivityBehaviour_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P56_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P57 {
	A_SEQUENCE_OF(struct S1AP_ForbiddenTAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P57_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P58 {
	A_SEQUENCE_OF(struct S1AP_ForbiddenLAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P58_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P59 {
	A_SEQUENCE_OF(struct S1AP_GBR_QosInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P59_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P60 {
	A_SEQUENCE_OF(struct S1AP_GUMMEI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P60_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P61 {
	A_SEQUENCE_OF(struct S1AP_HandoverRestrictionList_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P61_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P62 {
	A_SEQUENCE_OF(struct S1AP_ImmediateMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P62_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P63 {
	A_SEQUENCE_OF(struct S1AP_InformationOnRecommendedCellsAndENBsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P63_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P64 {
	A_SEQUENCE_OF(struct S1AP_LAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P64_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P65 {
	A_SEQUENCE_OF(struct S1AP_LastVisitedEUTRANCellInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P65_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P66 {
	A_SEQUENCE_OF(struct S1AP_ListeningSubframePattern_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P66_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P67 {
	A_SEQUENCE_OF(struct S1AP_LoggedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P67_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P68 {
	A_SEQUENCE_OF(struct S1AP_LoggedMBSFNMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P68_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P69 {
	A_SEQUENCE_OF(struct S1AP_M3Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P69_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P70 {
	A_SEQUENCE_OF(struct S1AP_M4Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P70_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P71 {
	A_SEQUENCE_OF(struct S1AP_M5Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P71_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P72 {
	A_SEQUENCE_OF(struct S1AP_M6Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P72_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P73 {
	A_SEQUENCE_OF(struct S1AP_M7Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P73_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P74 {
	A_SEQUENCE_OF(struct S1AP_MDT_Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P74_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P75 {
	A_SEQUENCE_OF(struct S1AP_MBSFN_ResultToLogInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P75_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P76 {
	A_SEQUENCE_OF(struct S1AP_MutingPatternInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P76_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P77 {
	A_SEQUENCE_OF(struct S1AP_NB_IoT_Paging_eDRXInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P77_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P78 {
	A_SEQUENCE_OF(struct S1AP_NRUESecurityCapabilities_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P78_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P79 {
	A_SEQUENCE_OF(struct S1AP_PagingAttemptInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P79_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P80 {
	A_SEQUENCE_OF(struct S1AP_Paging_eDRXInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P80_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P81 {
	A_SEQUENCE_OF(struct S1AP_M1PeriodicReporting_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P81_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P82 {
	A_SEQUENCE_OF(struct S1AP_PLMNAreaBasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P82_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P83 {
	A_SEQUENCE_OF(struct S1AP_ProSeAuthorized_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P83_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P84 {
	A_SEQUENCE_OF(struct S1AP_RecommendedCellsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P84_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P85 {
	A_SEQUENCE_OF(struct S1AP_RecommendedCellsForPagingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P85_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P86 {
	A_SEQUENCE_OF(struct S1AP_RecommendedENBsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P86_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P87 {
	A_SEQUENCE_OF(struct S1AP_RecommendedENBItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P87_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P88 {
	A_SEQUENCE_OF(struct S1AP_RequestType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P88_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P89 {
	A_SEQUENCE_OF(struct S1AP_RIMTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P89_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P90 {
	A_SEQUENCE_OF(struct S1AP_RLFReportInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P90_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P91 {
	A_SEQUENCE_OF(struct S1AP_SecurityContext_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P91_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P92 {
	A_SEQUENCE_OF(struct S1AP_SecondaryRATDataUsageReportItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P92_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P93 {
	A_SEQUENCE_OF(struct S1AP_SONInformationReply_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P93_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P94 {
	A_SEQUENCE_OF(struct S1AP_SONConfigurationTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P94_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P95 {
	A_SEQUENCE_OF(struct S1AP_SynchronisationInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P95_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P96 {
	A_SEQUENCE_OF(struct S1AP_SourceeNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P96_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P97 {
	A_SEQUENCE_OF(struct S1AP_SourceeNB_ToTargeteNB_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P97_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P98 {
	A_SEQUENCE_OF(struct S1AP_ServedGUMMEIsItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P98_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P99 {
	A_SEQUENCE_OF(struct S1AP_SupportedTAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P99_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P100 {
	A_SEQUENCE_OF(struct S1AP_TimeSynchronisationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P100_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P101 {
	A_SEQUENCE_OF(struct S1AP_S_TMSI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P101_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P102 {
	A_SEQUENCE_OF(struct S1AP_TAIBasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P102_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P103 {
	A_SEQUENCE_OF(struct S1AP_TAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P103_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P104 {
	A_SEQUENCE_OF(struct S1AP_TAI_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P104_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P105 {
	A_SEQUENCE_OF(struct S1AP_TAI_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P105_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P106 {
	A_SEQUENCE_OF(struct S1AP_TABasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P106_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P107 {
	A_SEQUENCE_OF(struct S1AP_TABasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P107_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P108 {
	A_SEQUENCE_OF(struct S1AP_TAIBasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P108_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P109 {
	A_SEQUENCE_OF(struct S1AP_CompletedCellinTAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P109_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P110 {
	A_SEQUENCE_OF(struct S1AP_TargeteNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P110_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P111 {
	A_SEQUENCE_OF(struct S1AP_TargetRNC_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P111_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P112 {
	A_SEQUENCE_OF(struct S1AP_TargeteNB_ToSourceeNB_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P112_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P113 {
	A_SEQUENCE_OF(struct S1AP_M1ThresholdEventA2_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P113_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P114 {
	A_SEQUENCE_OF(struct S1AP_TraceActivation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P114_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P115 {
	A_SEQUENCE_OF(struct S1AP_Tunnel_Information_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P115_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P116 {
	A_SEQUENCE_OF(struct S1AP_UEAggregate_MaximumBitrates_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P116_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P117 {
	A_SEQUENCE_OF(struct S1AP_UEAppLayerMeasConfig_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P117_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P118 {
	A_SEQUENCE_OF(struct S1AP_UE_S1AP_ID_pair_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P118_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P119 {
	A_SEQUENCE_OF(struct S1AP_UE_associatedLogicalS1_ConnectionItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P119_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P120 {
	A_SEQUENCE_OF(struct S1AP_UESecurityCapabilities_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P120_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P121 {
	A_SEQUENCE_OF(struct S1AP_UE_Sidelink_Aggregate_MaximumBitrates_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P121_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P122 {
	A_SEQUENCE_OF(struct S1AP_UL_CP_SecurityInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P122_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P123 {
	A_SEQUENCE_OF(struct S1AP_UserLocationInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P123_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P124 {
	A_SEQUENCE_OF(struct S1AP_V2XServicesAuthorized_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P124_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P125 {
	A_SEQUENCE_OF(struct S1AP_X2TNLConfigurationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P125_t;
typedef struct S1AP_ProtocolExtensionContainer_6890P126 {
	A_SEQUENCE_OF(struct S1AP_ENBX2ExtTLA_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolExtensionContainer_6890P126_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P0;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P0_specs_1;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P0_1[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P1;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P1_specs_3;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P1_3[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P2;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P2_specs_5;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P2_5[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P3;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P3_specs_7;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P3_7[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P4;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P4_specs_9;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P4_9[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P5;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P5_specs_11;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P5_11[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P6;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P6_specs_13;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P6_13[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P7;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P7_specs_15;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P7_15[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P8;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P8_specs_17;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P8_17[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P9;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P9_specs_19;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P9_19[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P10;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P10_specs_21;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P10_21[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P11;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P11_specs_23;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P11_23[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P12;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P12_specs_25;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P12_25[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P13;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P13_specs_27;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P13_27[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P14;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P14_specs_29;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P14_29[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P15;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P15_specs_31;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P15_31[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P16;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P16_specs_33;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P16_33[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P17;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P17_specs_35;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P17_35[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P18;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P18_specs_37;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P18_37[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P19;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P19_specs_39;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P19_39[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P20;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P20_specs_41;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P20_41[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P21;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P21_specs_43;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P21_43[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P22;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P22_specs_45;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P22_45[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P23;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P23_specs_47;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P23_47[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P24;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P24_specs_49;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P24_49[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P25;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P25_specs_51;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P25_51[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P26;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P26_specs_53;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P26_53[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P27;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P27_specs_55;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P27_55[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P28;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P28_specs_57;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P28_57[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P29;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P29_specs_59;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P29_59[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P30;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P30_specs_61;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P30_61[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P31;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P31_specs_63;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P31_63[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P32;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P32_specs_65;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P32_65[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P33;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P33_specs_67;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P33_67[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P34;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P34_specs_69;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P34_69[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P35;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P35_specs_71;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P35_71[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P36;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P36_specs_73;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P36_73[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P37;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P37_specs_75;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P37_75[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P38;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P38_specs_77;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P38_77[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P39;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P39_specs_79;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P39_79[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P40;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P40_specs_81;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P40_81[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P41;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P41_specs_83;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P41_83[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P42;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P42_specs_85;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P42_85[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P43;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P43_specs_87;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P43_87[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P44;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P44_specs_89;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P44_89[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P45;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P45_specs_91;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P45_91[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P46;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P46_specs_93;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P46_93[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P47;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P47_specs_95;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P47_95[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P48;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P48_specs_97;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P48_97[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P49;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P49_specs_99;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P49_99[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P50;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P50_specs_101;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P50_101[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P51;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P51_specs_103;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P51_103[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P52;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P52_specs_105;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P52_105[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P53;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P53_specs_107;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P53_107[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P54;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P54_specs_109;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P54_109[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P55;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P55_specs_111;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P55_111[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P56;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P56_specs_113;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P56_113[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P57;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P57_specs_115;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P57_115[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P58;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P58_specs_117;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P58_117[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P59;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P59_specs_119;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P59_119[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P60;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P60_specs_121;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P60_121[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P61;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P61_specs_123;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P61_123[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P62;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P62_specs_125;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P62_125[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P63;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P63_specs_127;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P63_127[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P64;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P64_specs_129;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P64_129[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P65;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P65_specs_131;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P65_131[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P66;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P66_specs_133;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P66_133[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P67;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P67_specs_135;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P67_135[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P68;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P68_specs_137;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P68_137[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P69;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P69_specs_139;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P69_139[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P70;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P70_specs_141;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P70_141[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P71;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P71_specs_143;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P71_143[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P72;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P72_specs_145;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P72_145[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P73;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P73_specs_147;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P73_147[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P74;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P74_specs_149;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P74_149[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P75;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P75_specs_151;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P75_151[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P76;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P76_specs_153;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P76_153[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P77;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P77_specs_155;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P77_155[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P78;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P78_specs_157;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P78_157[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P79;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P79_specs_159;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P79_159[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P80;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P80_specs_161;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P80_161[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P81;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P81_specs_163;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P81_163[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P82;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P82_specs_165;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P82_165[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P83;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P83_specs_167;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P83_167[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P84;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P84_specs_169;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P84_169[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P85;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P85_specs_171;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P85_171[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P86;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P86_specs_173;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P86_173[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P87;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P87_specs_175;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P87_175[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P88;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P88_specs_177;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P88_177[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P89;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P89_specs_179;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P89_179[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P90;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P90_specs_181;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P90_181[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P91;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P91_specs_183;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P91_183[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P92;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P92_specs_185;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P92_185[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P93;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P93_specs_187;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P93_187[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P94;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P94_specs_189;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P94_189[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P95;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P95_specs_191;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P95_191[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P96;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P96_specs_193;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P96_193[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P97;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P97_specs_195;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P97_195[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P98;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P98_specs_197;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P98_197[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P99;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P99_specs_199;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P99_199[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P100;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P100_specs_201;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P100_201[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P101;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P101_specs_203;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P101_203[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P102;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P102_specs_205;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P102_205[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P103;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P103_specs_207;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P103_207[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P104;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P104_specs_209;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P104_209[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P105;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P105_specs_211;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P105_211[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P106;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P106_specs_213;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P106_213[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P107;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P107_specs_215;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P107_215[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P108;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P108_specs_217;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P108_217[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P109;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P109_specs_219;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P109_219[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P110;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P110_specs_221;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P110_221[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P111;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P111_specs_223;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P111_223[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P112;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P112_specs_225;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P112_225[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P113;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P113_specs_227;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P113_227[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P114;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P114_specs_229;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P114_229[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P115;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P115_specs_231;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P115_231[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P116;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P116_specs_233;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P116_233[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P117;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P117_specs_235;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P117_235[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P118;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P118_specs_237;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P118_237[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P119;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P119_specs_239;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P119_239[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P119_constr_239;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P120;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P120_specs_241;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P120_241[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P120_constr_241;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P121;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P121_specs_243;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P121_243[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P121_constr_243;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P122;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P122_specs_245;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P122_245[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P122_constr_245;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P123;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P123_specs_247;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P123_247[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P123_constr_247;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P124;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P124_specs_249;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P124_249[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P124_constr_249;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P125;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P125_specs_251;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P125_251[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P125_constr_251;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolExtensionContainer_6890P126;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolExtensionContainer_6890P126_specs_253;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolExtensionContainer_6890P126_253[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolExtensionContainer_6890P126_constr_253;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
