/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "/home/lionel/EURECOM/CODE/openair-cn.prose.clean/src/s1ap/messages/asn1/r15/s1ap-15.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D /home/lionel/EURECOM/CODE/openair-cn.prose.clean/src/s1ap/messages/asn1/r15/GENERATED_S1AP`
 */

#ifndef	_S1AP_ProtocolIE_ContainerList_H_
#define	_S1AP_ProtocolIE_ContainerList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1AP_ProtocolIE_SingleContainer;

/* S1AP_ProtocolIE-ContainerList */
typedef struct S1AP_ProtocolIE_ContainerList_6876P0 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P0_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P1 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P1_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P2 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P2_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P3 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P3_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P4 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P4_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P5 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P5_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P6 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P6_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P7 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P7_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P8 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P8_t;
typedef struct S1AP_ProtocolIE_ContainerList_6876P9 {
	A_SEQUENCE_OF(struct S1AP_ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ProtocolIE_ContainerList_6876P9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P0;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P0_specs_1;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P0_1[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P1;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P1_specs_3;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P1_3[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P2;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P2_specs_5;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P2_5[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P3;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P3_specs_7;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P3_7[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P4;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P4_specs_9;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P4_9[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P5;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P5_specs_11;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P5_11[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P6;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P6_specs_13;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P6_13[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P7;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P7_specs_15;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P7_15[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P8;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P8_specs_17;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P8_17[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ProtocolIE_ContainerList_6876P9;
extern asn_SET_OF_specifics_t asn_SPC_S1AP_ProtocolIE_ContainerList_6876P9_specs_19;
extern asn_TYPE_member_t asn_MBR_S1AP_ProtocolIE_ContainerList_6876P9_19[1];
extern asn_per_constraints_t asn_PER_type_S1AP_ProtocolIE_ContainerList_6876P9_constr_19;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_ProtocolIE_ContainerList_H_ */
#include <asn_internal.h>
